name: "🐞 Bug report"
description: Report a problem with @yudiel/react-qr-scanner
title: "[Bug]: "
labels: ["bug", "needs triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Please reproduce the issue in the sandbox and paste the **Copy debug info** JSON below.
        ▶️ Sandbox: https://codesandbox.io/p/sandbox/yudiel-react-qr-scanner-ts3lgn

  - type: checkboxes
    id: prechecks
    attributes:
      label: Pre-checks
      options:
        - label: I used HTTPS or localhost (required for camera).
          required: true
        - label: I allowed camera permissions and no other app/tab is using the camera.
          required: true
        - label: I reproduced the issue in the sandbox (or a minimal public repo).
          required: true

  - type: input
    id: repro_link
    attributes:
      label: Reproduction link
      description: CodeSandbox URL (preferred) or public repo.
      placeholder: https://codesandbox.io/p/sandbox/yudiel-react-qr-scanner-ts3lgn
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Numbered, concise steps.
      placeholder: |
        1) Open sandbox, allow camera
        2) Select device: Back Camera
        3) Tracker: outline; Formats: qr_code
        4) Scan sample QR → error appears
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Scanner should detect QR code within ~1s and log value
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: No detections; console shows NotAllowedError
    validations:
      required: true

  - type: dropdown
    id: tracker
    attributes:
      label: Built-in tracker used
      options:
        - none
        - centerText
        - outline
        - boundingBox
      default: 0

  - type: checkboxes
    id: components
    attributes:
      label: Built-in UI components used
      options:
        - label: onOff
        - label: torch
        - label: zoom
        - label: finder

  - type: checkboxes
    id: formats
    attributes:
      label: Formats attempted
      options:
        - label: qr_code
        - label: ean_13
        - label: code_128
        - label: data_matrix
        - label: pdf417
        - label: others (see debug JSON)

  - type: textarea
    id: debug_json
    attributes:
      label: Paste "Copy debug info" JSON from the sandbox (required)
      description: From the sandbox's Copy debug info button.
      render: json
      placeholder: |
        {
          "timestamp": "...",
          "libraryVersion": "...",
          "userAgent": "...",
          "permissions": {"camera": "..."},
          "barcodeDetector": {"present": true, "supportedFormats": [...]},
          "availableDevices": [...],
          "selectedDeviceId": "...",
          "props": {"formats": [...], "paused": false, "scanDelay": 500, ...},
          "lastError": null,
          "recentLogs": [...]
        }
    validations:
      required: true

  - type: input
    id: lib_version
    attributes:
      label: Library version
      placeholder: e.g. 2.3.1
    validations:
      required: true

  - type: input
    id: react_version
    attributes:
      label: React version
      placeholder: 18.3.x or 19.0.0
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, browser, device model (and whether mobile/desktop).
      placeholder: |
        OS: iOS 17.5.1
        Browser: Safari 17
        Device: iPhone 13 (rear camera)
        Mobile/Desktop: Mobile
      render: bash
    validations:
      required: true

  - type: textarea
    id: console
    attributes:
      label: Console output (errors/warnings)
      render: bash

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / recordings
      description: Drag-and-drop images or screen recordings.

  - type: textarea
    id: notes
    attributes:
      label: Additional context
      description: Anything else that might help diagnose the issue.